cargo-features = ["edition2024"]

[package]
name = "contract"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "1.18.26"
